name: OpenSSH
on:
  workflow_dispatch
jobs:
    build-aarch64:
      name: Build OpenSSH AARCH64
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.build_openssh.outputs.PACKAGED_VERSION }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build OpenSSH
          id: build_openssh
          run: |
            mkdir -p ${{ github.workspace }}/output
            touch ${{ github.workspace }}/github_output.env
            docker run --rm \
              -v ${{ github.workspace }}:/workspace \
              -v ${{ github.workspace }}/output:/output \
              -w /workspace \
              -e GITHUB_WORKSPACE=/workspace \
              -e GITHUB_OUTPUT=/workspace/github_output.env \
              muslcc/x86_64:aarch64-linux-musl \
              sh -c "apk update && apk add bash && bash build/install_deps_alpine.sh && bash build/targets/build_openssh.sh aarch64"
            sed -i "s|/output/|${{ github.workspace }}/output/|g" ${{ github.workspace }}/github_output.env
            cat ${{ github.workspace }}/github_output.env >> $GITHUB_OUTPUT

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
              name: ${{ steps.build_openssh.outputs.PACKAGED_NAME }}
              path: ${{ steps.build_openssh.outputs.PACKAGED_NAME_PATH }}

    create-release:
      name: Create OpenSSH Release
      runs-on: ubuntu-latest
      needs: [build-aarch64]
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Prepare Environment
          run: mkdir -p /tmp/releases

        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            path: /tmp/releases

        - name: List Artifacts
          run: ls -laR /tmp/releases

        - name: Tag Release
          id: tag_release
          run: |
            set +e
            if git rev-list "openssh-v${{ needs.build-aarch64.outputs.version }}".. >/dev/null;then
              echo "NEW_RELEASE=false" >> $GITHUB_OUTPUT
            else
              git tag "openssh-v${{ needs.build-aarch64.outputs.version }}"
              git push origin "openssh-v${{ needs.build-aarch64.outputs.version }}"
              echo "NEW_RELEASE=true" >> $GITHUB_OUTPUT
            fi

        - name: Create Release
          uses: ncipollo/release-action@v1
          if: ${{ steps.tag_release.outputs.NEW_RELEASE == 'true' }}
          with:
            name: openssh-v${{ needs.build-aarch64.outputs.version }}
            tag: openssh-v${{ needs.build-aarch64.outputs.version }}
            artifacts: "/tmp/releases/*/*"
            token: ${{ secrets.GITHUB_TOKEN }}